image: alpine/latest
packages:
  - go
  - rsync
sources:
  - https://github.com/sauerbraten/extinfo-web
environment:
  DEPLOY: p1x.pw
  GOFLAGS: '-mod=vendor'
secrets:
  - 41a695fb-4229-450d-9aa4-5499f6bcea81 # ssh key
tasks:
  - build: |
      cd extinfo-web
      go build
  - deploy: |
      cd extinfo-web
      rsync --rsh="ssh -o StrictHostKeyChecking=no" -rPq css html js extinfo-web ci@$DEPLOY:~/extinfo-web/
      ssh -o StrictHostKeyChecking=no ci@$DEPLOY 'killall extinfo-web || true'
      ssh -o StrictHostKeyChecking=no ci@$DEPLOY 'cd extinfo-web; nohup ./extinfo-web >> log.txt 2>&1 &'
